add program to compare template with fingerprint folfer
adafruit/Adafruit_CircuitPython_Fingerprint pull request #55
Opened 2024-10-03 01:05 UTC by itsFDavid

Added example of program to compare fingerprint with template folder and added more functions how that store image, store template on fingerprint folder, store model on sensor

2024-10-07 15:02 UTC, FoamyGuy requested changes
Thanks for working on this @itsFDavid. 

It looks mostly good to me, but there are a few tweaks I think should be:

- updating the copyright information
- add "rpi" at the end of the new filename to designate this example is not meant for microcontrollers

2024-10-07 15:02 UTC, FoamyGuy commented on examples/fingerprint_template_folder_compare_with_file.py
> +# SPDX-License-Identifier: MIT
```suggestion
# SPDX-FileCopyrightText: 2024 itsFDavid
# SPDX-License-Identifier: MIT
```

2024-10-07 15:02 UTC, FoamyGuy commented on examples/fingerprint_template_folder_compare_with_file.py
> +# SPDX-License-Identifier: MIT
The copyright should be updated to the correct year and to you

2024-10-08 04:08 UTC, itsFDavid commented on examples/fingerprint_template_folder_compare_with_file.py
> +# SPDX-License-Identifier: MIT
ok, thanks for viewed my file, now i change this

2024-11-02 21:36 UTC, FoamyGuy approved these changes
This looks good to me, thank you @itsFDavid!

I didn't test on hardware but seems good to me.

2024-11-02 21:36 UTC, merged